---
jobs:
- name: build-unit-test
  public: true
  serial: true
  plan:
  - aggregate:
    - get: dynatrace-service-broker-source-code
    - get: my-code
    - get: rc-version
      resource: app-version
      params:
        bump: minor
        pre: rc
  - task: build-unit-test
    config:
      platform: linux
      image: docker:///jamesdbloom/docker-java8-maven
      inputs:
        - name: dynatrace-service-broker-source-code
        - name: my-code
        - name: rc-version
      run:
        path: my-code/build-task.sh
        args: [rc-version/number]
  - task: display-file-structure
    config:
      platform: linux
      run:
        path: ls
        args: [.]
  - put: rc-version
    resource: app-version
    params: 
      file: rc-version/number
  - put: artifact-repo
    params:
      from: build-unit-test/target/dynatrace-service-broker-.*.jar

# - name: dev-deploy
#   public: true
#   serial: true
#   plan:
#   - aggregate:
#     - get: my-code
#    - get: artifact-repo
#      params:
#        filename: dynatrace-service-broker-*.jar
#        version: rc-version/number
#   - aggregate:
#     - task: debug-artificate-repo
#       config:
#         platform: linux
#         inputs:
#           #- name: artifact-repo
#           - name: build-unit-test
#         run:
#           path: ls
#           args: [build-unit-test]
#   - aggregate:
#     - put: dev-cf
#       params:
#         manifest: my-code/manifest.yml
#         path: artifact-repo/dynatrace-service-broker-0.1.0-rc.17.jar

resources:
- name: dynatrace-service-broker-source-code
  type: git
  source:
    uri: https://github.com/owaism/dynatrace-service-broker.git
- name: my-code
  type: git
  source:
    uri: https://github.com/owaism/dynatrace-concourse-poc.git
- name: dev-cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false
- name: artifact-repo
  type: s3
  source:
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    bucket: {{s3-rc-artifact-bucket}}
    regexp: dynatrace-service-broker-([0-9]+\.[0-9]+\.[0-9]+)\.jar
    endpoint: s3-us-west-2.amazonaws.com
- name: app-version
  type: semver
  source:
    bucket: {{s3-artifact-version-bucket}}
    key: current-version
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    endpoint: s3-us-west-2.amazonaws.com
