---
jobs:
- name: build-unit-test
  public: true
  serial: true
  plan:
  - aggregate:
    - get: dynatrace-service-broker-source-code
    - get: my-code
    - get: rc-version
      params:
        bump: minor
        pre: rc
  - aggregate:
      - task: build-unit-test
        config:
          platform: linux
          image: docker:///jamesdbloom/docker-java8-maven
          inputs:
            - name: dynatrace-service-broker-source-code
            - name: my-code
            - name: rc-version
          run:
            path: my-code/build-task.sh
            args: [rc-version/number]
  - aggregate:
    - put: artifact-repo
      params:
        from: dynatrace-service-broker-source-code/target/dynatrace-service-broker-.*.jar
- name: dev-deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: dynatrace-service-broker-source-code
  - aggregate:
    - task: build-app
      file: build-task.yml
  - aggregate:
    - put: dev-cf
      params:
        manifest: dynatrace-service-broker-source-code/manifest.yml
        path: dynatrace-service-broker-source-code

resources:
- name: dynatrace-service-broker-source-code
  type: git
  source:
    uri: https://github.com/owaism/dynatrace-service-broker.git
- name: my-code
  type: git
  source:
    uri: https://github.com/owaism/dynatrace-concourse-poc.git
- name: dev-cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false
- name: artifact-repo
  type: s3
  source:
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    bucket: {{s3-rc-artifact-bucket}}
    regexp: dynatrace-service-broker-([0-9]+\.[0-9]+\.[0-9]+)\.jar
    endpoint: s3-us-west-2.amazonaws.com
- name: rc-version
  type: semver
  source:
    bucket: {{s3-artifact-version-bucket}}
    key: current-version
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    endpoint: s3-us-west-2.amazonaws.com
